package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * As400BillShipInformation generated by hbm2java
 */
@Entity
@Table(name = "AS400_BILL_SHIP_INFORMATION")
public class As400BillShipInformation implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private long billShipId;

	private As400Customers as400Customers;

	private String attention;

	private String billShipType;

	private String customerName;

	private String address1;

	private String address2;

	private String city;

	private String state;

	private String postalCode;

	// private String orderNumber;

	// private String orderSuffix;

	private Set<As400ContactInformation> as400ContactInformations = new HashSet<As400ContactInformation>(
			0);

	// bi-directional many-to-one association to As400Order
	private As400Orders as400Orders;

	public As400BillShipInformation() {
	}

	public As400BillShipInformation(long billShipId) {
		this.billShipId = billShipId;
	}

	public As400BillShipInformation(long billShipId,
			As400Customers as400Customers, String attention,
			String billShipType, String customerName, String address1,
			String address2, String city, String state, String postalCode,
			String orderNumber, String orderSuffix,
			Set<As400ContactInformation> as400ContactInformations) {
		this.billShipId = billShipId;
		this.as400Customers = as400Customers;
		this.attention = attention;
		this.billShipType = billShipType;
		this.customerName = customerName;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.postalCode = postalCode;
		// this.orderNumber = orderNumber;
		// this.orderSuffix = orderSuffix;
		this.as400ContactInformations = as400ContactInformations;
	}

	/**
	 * @return the as400Orders
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ORDER_NUMBER", referencedColumnName = "ORDER_NUMBER"),
			@JoinColumn(name = "ORDER_SUFFIX", referencedColumnName = "ORDER_SUFFIX") })
	public As400Orders getAs400Orders() {
		return as400Orders;
	}

	/**
	 * @param as400Orders
	 *            the as400Orders to set
	 */
	public void setAs400Orders(As400Orders as400Orders) {
		this.as400Orders = as400Orders;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Id
	@Column(name = "BILL_SHIP_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getBillShipId() {
		return this.billShipId;
	}

	public void setBillShipId(long billShipId) {
		this.billShipId = billShipId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_NUMBER")
	public As400Customers getAs400Customers() {
		return this.as400Customers;
	}

	public void setAs400Customers(As400Customers as400Customers) {
		this.as400Customers = as400Customers;
	}

	@Column(name = "ATTENTION", length = 30)
	public String getAttention() {
		return this.attention;
	}

	public void setAttention(String attention) {
		this.attention = attention;
	}

	@Column(name = "BILL_SHIP_TYPE", length = 4)
	public String getBillShipType() {
		return this.billShipType;
	}

	public void setBillShipType(String billShipType) {
		this.billShipType = billShipType;
	}

	@Column(name = "CUSTOMER_NAME", length = 30)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "ADDRESS1", length = 225)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "ADDRESS2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "CITY", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "POSTAL_CODE", length = 10)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	// @Column(name = "ORDER_NUMBER", length = 30)
	// public String getOrderNumber() {
	// return this.orderNumber;
	// }
	//
	// public void setOrderNumber(String orderNumber) {
	// this.orderNumber = orderNumber;
	// }

	// @Column(name = "ORDER_SUFFIX", length = 2)
	// public String getOrderSuffix() {
	// return this.orderSuffix;
	// }
	//
	// public void setOrderSuffix(String orderSuffix) {
	// this.orderSuffix = orderSuffix;
	// }

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "as400BillShipInformation")
	public Set<As400ContactInformation> getAs400ContactInformations() {
		return this.as400ContactInformations;
	}

	public void setAs400ContactInformations(
			Set<As400ContactInformation> as400ContactInformations) {
		this.as400ContactInformations = as400ContactInformations;
	}

}
