package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * As400OrdersItems generated by hbm2java
 */
@Entity
@Table(name = "AS400_ORDERS_ITEMS")
public class As400OrdersItems implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private As400OrdersItemsId id;

	private Integer quantity;

	public As400OrdersItems() {
	}

	public As400OrdersItems(As400OrdersItemsId id) {
		this.id = id;
	}

	public As400OrdersItems(As400OrdersItemsId id, Integer quantity) {
		this.id = id;
		this.quantity = quantity;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "orderNumber", column = @Column(name = "ORDER_NUMBER", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "orderSuffix", column = @Column(name = "ORDER_SUFFIX", nullable = false, length = 2)),
			@AttributeOverride(name = "bookNumber", column = @Column(name = "BOOK_NUMBER", nullable = false, precision = 7, scale = 0)) })
	public As400OrdersItemsId getId() {
		return this.id;
	}

	public void setId(As400OrdersItemsId id) {
		this.id = id;
	}

	@Column(name = "QUANTITY", precision = 8, scale = 0)
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
