package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * As400Customers generated by hbm2java
 */
@Entity
@Table(name = "AS400_CUSTOMERS")
public class As400Customers implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int customerNumber;

	private String customerName;

	private String addressLine1;

	private String city;

	private String nation;

	private String state;

	private String postalCode;

	private String phoneNumber;

	private Short phoneExt;

	private String mdrPid;

	private String faxPhoneNo;

	private String recordActiveInactive;

	private Set<As400BillShipInformation> as400BillShipInformations = new HashSet<As400BillShipInformation>(
			0);

	private Set<As400ProfileInformation> as400ProfileInformations = new HashSet<As400ProfileInformation>(
			0);

	// Not directly through billship
	// private Set<As400ContactInformation> as400ContactInformations = new
	// HashSet<As400ContactInformation>(
	// 0);

	// remove
	// private Set<As400Orders> as400Orderses = new HashSet<As400Orders>(0);

	public As400Customers() {
	}

	public As400Customers(int customerNumber) {
		this.customerNumber = customerNumber;
	}

	public As400Customers(int customerNumber, String customerName,
			String addressLine1, String city, String nation, String state,
			String postalCode, String phoneNumber, Short phoneExt,
			String mdrPid, String faxPhoneNo, String recordActiveInactive,
			Set<As400BillShipInformation> as400BillShipInformations,
			Set<As400ProfileInformation> as400ProfileInformations,
			Set<As400ContactInformation> as400ContactInformations,
			Set<As400Orders> as400Orderses) {
		this.customerNumber = customerNumber;
		this.customerName = customerName;
		this.addressLine1 = addressLine1;
		this.city = city;
		this.nation = nation;
		this.state = state;
		this.postalCode = postalCode;
		this.phoneNumber = phoneNumber;
		this.phoneExt = phoneExt;
		this.mdrPid = mdrPid;
		this.faxPhoneNo = faxPhoneNo;
		this.recordActiveInactive = recordActiveInactive;
		this.as400BillShipInformations = as400BillShipInformations;
		this.as400ProfileInformations = as400ProfileInformations;
		// this.as400ContactInformations = as400ContactInformations;
		// this.as400Orderses = as400Orderses;
	}

	@Id
	@Column(name = "CUSTOMER_NUMBER", unique = true, nullable = false, precision = 7, scale = 0)
	public int getCustomerNumber() {
		return this.customerNumber;
	}

	public void setCustomerNumber(int customerNumber) {
		this.customerNumber = customerNumber;
	}

	@Column(name = "CUSTOMER_NAME", length = 30)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "ADDRESS_LINE_1", length = 30)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "CITY", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "NATION", length = 2)
	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	@Column(name = "STATE", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "POSTAL_CODE", length = 10)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "PHONE_NUMBER", length = 12)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "PHONE_EXT", precision = 4, scale = 0)
	public Short getPhoneExt() {
		return this.phoneExt;
	}

	public void setPhoneExt(Short phoneExt) {
		this.phoneExt = phoneExt;
	}

	@Column(name = "MDR_PID", length = 8)
	public String getMdrPid() {
		return this.mdrPid;
	}

	public void setMdrPid(String mdrPid) {
		this.mdrPid = mdrPid;
	}

	@Column(name = "FAX_PHONE_NO", length = 12)
	public String getFaxPhoneNo() {
		return this.faxPhoneNo;
	}

	public void setFaxPhoneNo(String faxPhoneNo) {
		this.faxPhoneNo = faxPhoneNo;
	}

	@Column(name = "RECORD_ACTIVE_INACTIVE", length = 1)
	public String getRecordActiveInactive() {
		return this.recordActiveInactive;
	}

	public void setRecordActiveInactive(String recordActiveInactive) {
		this.recordActiveInactive = recordActiveInactive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "as400Customers")
	public Set<As400BillShipInformation> getAs400BillShipInformations() {
		return this.as400BillShipInformations;
	}

	public void setAs400BillShipInformations(
			Set<As400BillShipInformation> as400BillShipInformations) {
		this.as400BillShipInformations = as400BillShipInformations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "as400Customers")
	public Set<As400ProfileInformation> getAs400ProfileInformations() {
		return this.as400ProfileInformations;
	}

	public void setAs400ProfileInformations(
			Set<As400ProfileInformation> as400ProfileInformations) {
		this.as400ProfileInformations = as400ProfileInformations;
	}

	// @OneToMany(fetch = FetchType.LAZY, mappedBy = "as400Customers")
	// public Set<As400ContactInformation> getAs400ContactInformations() {
	// return this.as400ContactInformations;
	// }
	//
	// public void setAs400ContactInformations(
	// Set<As400ContactInformation> as400ContactInformations) {
	// this.as400ContactInformations = as400ContactInformations;
	// }

	// @OneToMany(fetch = FetchType.LAZY, mappedBy = "as400Customers")
	// public Set<As400Orders> getAs400Orderses() {
	// return this.as400Orderses;
	// }
	//
	// public void setAs400Orderses(Set<As400Orders> as400Orderses) {
	// this.as400Orderses = as400Orderses;
	// }

}
