package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * As400Items generated by hbm2java
 */
@Entity
@Table(name = "AS400_ITEMS")
public class As400Items implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String bookNumber;

	private String title;

	private String author;

	private Short copyrightYear;

	private String vendorNumber;

	private String publisherCode;

	private String vendorProductNumber;

	private String subject;

	private String productCategory;

	private String publisher;

	private String upcCode;

	private String edition;

	private String bookType;

	// this field is mapped with isbn10 and 13 is still remaining.
	private String isbn;

	private Short readingLevel;

	private String bookNotes;

	private String titleInformation;

	private String fesBookNumber;

	private String warehouseCode;

	private String waveAccRedIntLvl;

	private String itemDescription;

	private String publisherItemNum;

	public As400Items() {
	}

	public As400Items(String bookNumber) {
		this.bookNumber = bookNumber;
	}

	public As400Items(String bookNumber, String title, String author,
			Short copyrightYear, String vendorNumber, String publisherCode,
			String vendorProductNumber, String subject, String productCategory,
			String publisher, String upcCode, String edition, String bookType,
			String isbn, Short readingLevel, String bookNotes,
			String titleInformation, String fesBookNumber,
			String warehouseCode, String waveAccRedIntLvl,
			String itemDescription, String publisherItemNum) {
		this.bookNumber = bookNumber;
		this.title = title;
		this.author = author;
		this.copyrightYear = copyrightYear;
		this.vendorNumber = vendorNumber;
		this.publisherCode = publisherCode;
		this.vendorProductNumber = vendorProductNumber;
		this.subject = subject;
		this.productCategory = productCategory;
		this.publisher = publisher;
		this.upcCode = upcCode;
		this.edition = edition;
		this.bookType = bookType;
		this.isbn = isbn;
		this.readingLevel = readingLevel;
		this.bookNotes = bookNotes;
		this.titleInformation = titleInformation;
		this.fesBookNumber = fesBookNumber;
		this.warehouseCode = warehouseCode;
		this.waveAccRedIntLvl = waveAccRedIntLvl;
		this.itemDescription = itemDescription;
		this.publisherItemNum = publisherItemNum;
	}

	@Id
	@Column(name = "BOOK_NUMBER", unique = true, nullable = false, length = 7)
	public String getBookNumber() {
		return this.bookNumber;
	}

	public void setBookNumber(String bookNumber) {
		this.bookNumber = bookNumber;
	}

	@Column(name = "TITLE", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "AUTHOR", length = 50)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "COPYRIGHT_YEAR", precision = 4, scale = 0)
	public Short getCopyrightYear() {
		return this.copyrightYear;
	}

	public void setCopyrightYear(Short copyrightYear) {
		this.copyrightYear = copyrightYear;
	}

	@Column(name = "VENDOR_NUMBER", length = 4)
	public String getVendorNumber() {
		return this.vendorNumber;
	}

	public void setVendorNumber(String vendorNumber) {
		this.vendorNumber = vendorNumber;
	}

	@Column(name = "PUBLISHER_CODE", length = 4)
	public String getPublisherCode() {
		return this.publisherCode;
	}

	public void setPublisherCode(String publisherCode) {
		this.publisherCode = publisherCode;
	}

	@Column(name = "VENDOR_PRODUCT_NUMBER", length = 10)
	public String getVendorProductNumber() {
		return this.vendorProductNumber;
	}

	public void setVendorProductNumber(String vendorProductNumber) {
		this.vendorProductNumber = vendorProductNumber;
	}

	@Column(name = "SUBJECT", length = 4)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "PRODUCT_CATEGORY", length = 20)
	public String getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(String productCategory) {
		this.productCategory = productCategory;
	}

	@Column(name = "PUBLISHER", length = 100)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "UPC_CODE", length = 11)
	public String getUpcCode() {
		return this.upcCode;
	}

	public void setUpcCode(String upcCode) {
		this.upcCode = upcCode;
	}

	@Column(name = "EDITION", length = 20)
	public String getEdition() {
		return this.edition;
	}

	public void setEdition(String edition) {
		this.edition = edition;
	}

	@Column(name = "BOOK_TYPE", length = 30)
	public String getBookType() {
		return this.bookType;
	}

	public void setBookType(String bookType) {
		this.bookType = bookType;
	}

	@Column(name = "ISBN10", length = 13)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "READING_LEVEL", precision = 4, scale = 0)
	public Short getReadingLevel() {
		return this.readingLevel;
	}

	public void setReadingLevel(Short readingLevel) {
		this.readingLevel = readingLevel;
	}

	@Column(name = "BOOK_NOTES", length = 60)
	public String getBookNotes() {
		return this.bookNotes;
	}

	public void setBookNotes(String bookNotes) {
		this.bookNotes = bookNotes;
	}

	@Column(name = "TITLE_INFORMATION", length = 100)
	public String getTitleInformation() {
		return this.titleInformation;
	}

	public void setTitleInformation(String titleInformation) {
		this.titleInformation = titleInformation;
	}

	@Column(name = "FES_BOOK_NUMBER", length = 7)
	public String getFesBookNumber() {
		return this.fesBookNumber;
	}

	public void setFesBookNumber(String fesBookNumber) {
		this.fesBookNumber = fesBookNumber;
	}

	@Column(name = "WAREHOUSE_CODE", length = 10)
	public String getWarehouseCode() {
		return this.warehouseCode;
	}

	public void setWarehouseCode(String warehouseCode) {
		this.warehouseCode = warehouseCode;
	}

	@Column(name = "WAVE_ACC_RED_INT_LVL", length = 2)
	public String getWaveAccRedIntLvl() {
		return this.waveAccRedIntLvl;
	}

	public void setWaveAccRedIntLvl(String waveAccRedIntLvl) {
		this.waveAccRedIntLvl = waveAccRedIntLvl;
	}

	@Column(name = "ITEM_DESCRIPTION", length = 225)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "PUBLISHER_ITEM_NUM", length = 7)
	public String getPublisherItemNum() {
		return this.publisherItemNum;
	}

	public void setPublisherItemNum(String publisherItemNum) {
		this.publisherItemNum = publisherItemNum;
	}

}
