package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * As400TrackingInformation generated by hbm2java
 */
@Entity
@Table(name = "AS400_TRACKING_INFORMATION")
public class As400TrackingInformation implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private BigDecimal trackingId;

	private As400Orders as400Orders;

	private String shipmentMethod;

	private Date shippedDate;

	private Date invoiceDate;

	private Long totalInvoice;

	private String invoiceBatchNumber;

	private Date shipOrderOnDate;

	public As400TrackingInformation() {
	}

	public As400TrackingInformation(BigDecimal trackingId) {
		this.trackingId = trackingId;
	}

	public As400TrackingInformation(BigDecimal trackingId,
			As400Orders as400Orders, String shipmentMethod, Date shippedDate,
			Date invoiceDate, Long totalInvoice, String invoiceBatchNumber,
			Date shipOrderOnDate) {
		this.trackingId = trackingId;
		this.as400Orders = as400Orders;
		this.shipmentMethod = shipmentMethod;
		this.shippedDate = shippedDate;
		this.invoiceDate = invoiceDate;
		this.totalInvoice = totalInvoice;
		this.invoiceBatchNumber = invoiceBatchNumber;
		this.shipOrderOnDate = shipOrderOnDate;
	}

	@Id
	@Column(name = "TRACKING_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTrackingId() {
		return this.trackingId;
	}

	public void setTrackingId(BigDecimal trackingId) {
		this.trackingId = trackingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ORDER_NUMBER", referencedColumnName = "ORDER_NUMBER"),
			@JoinColumn(name = "ORDER_SUFFIX", referencedColumnName = "ORDER_SUFFIX") })
	public As400Orders getAs400Orders() {
		return this.as400Orders;
	}

	public void setAs400Orders(As400Orders as400Orders) {
		this.as400Orders = as400Orders;
	}

	@Column(name = "SHIPMENT_METHOD", length = 10)
	public String getShipmentMethod() {
		return this.shipmentMethod;
	}

	public void setShipmentMethod(String shipmentMethod) {
		this.shipmentMethod = shipmentMethod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SHIPPED_DATE")
	public Date getShippedDate() {
		return this.shippedDate;
	}

	public void setShippedDate(Date shippedDate) {
		this.shippedDate = shippedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INVOICE_DATE", length = 7)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Column(name = "TOTAL_INVOICE", precision = 10, scale = 0)
	public Long getTotalInvoice() {
		return this.totalInvoice;
	}

	public void setTotalInvoice(Long totalInvoice) {
		this.totalInvoice = totalInvoice;
	}

	@Column(name = "INVOICE_BATCH_NUMBER", length = 6)
	public String getInvoiceBatchNumber() {
		return this.invoiceBatchNumber;
	}

	public void setInvoiceBatchNumber(String invoiceBatchNumber) {
		this.invoiceBatchNumber = invoiceBatchNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SHIP_ORDER_ON_DATE", length = 7)
	public Date getShipOrderOnDate() {
		return this.shipOrderOnDate;
	}

	public void setShipOrderOnDate(Date shipOrderOnDate) {
		this.shipOrderOnDate = shipOrderOnDate;
	}

}
