package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * As400OrdersId generated by hbm2java
 */
@Embeddable
public class As400OrdersId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int orderNumber;

	private String orderSuffix;

	public As400OrdersId() {
	}

	public As400OrdersId(int orderNumber, String orderSuffix) {
		this.orderNumber = orderNumber;
		this.orderSuffix = orderSuffix;
	}

	@Column(name = "ORDER_NUMBER", nullable = false, precision = 7, scale = 0)
	public int getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(int orderNumber) {
		this.orderNumber = orderNumber;
	}

	@Column(name = "ORDER_SUFFIX", nullable = false, length = 2)
	public String getOrderSuffix() {
		return this.orderSuffix;
	}

	public void setOrderSuffix(String orderSuffix) {
		this.orderSuffix = orderSuffix;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof As400OrdersId))
			return false;
		As400OrdersId castOther = (As400OrdersId) other;

		return (this.getOrderNumber() == castOther.getOrderNumber())
				&& ((this.getOrderSuffix() == castOther.getOrderSuffix()) || (this
						.getOrderSuffix() != null
						&& castOther.getOrderSuffix() != null && this
						.getOrderSuffix().equals(castOther.getOrderSuffix())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderNumber();
		result = 37
				* result
				+ (getOrderSuffix() == null ? 0 : this.getOrderSuffix()
						.hashCode());
		return result;
	}

}
