package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * As400ProfileInformation generated by hbm2java
 */
@Entity
@Table(name = "AS400_PROFILE_INFORMATION")
public class As400ProfileInformation implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private BigDecimal profileId;

	private As400Customers as400Customers;

	private String classOfTrade;

	public As400ProfileInformation() {
	}

	public As400ProfileInformation(BigDecimal profileId) {
		this.profileId = profileId;
	}

	public As400ProfileInformation(BigDecimal profileId,
			As400Customers as400Customers, String classOfTrade) {
		this.profileId = profileId;
		this.as400Customers = as400Customers;
		this.classOfTrade = classOfTrade;
	}

	@Id
	@Column(name = "PROFILE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProfileId() {
		return this.profileId;
	}

	public void setProfileId(BigDecimal profileId) {
		this.profileId = profileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_NUMBER")
	public As400Customers getAs400Customers() {
		return this.as400Customers;
	}

	public void setAs400Customers(As400Customers as400Customers) {
		this.as400Customers = as400Customers;
	}

	@Column(name = "CLASS_OF_TRADE", length = 1)
	public String getClassOfTrade() {
		return this.classOfTrade;
	}

	public void setClassOfTrade(String classOfTrade) {
		this.classOfTrade = classOfTrade;
	}

}
