package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MfBillShipInformation generated by hbm2java
 */
@Entity
@Table(name = "MF_BILL_SHIP_INFORMATION")
public class MfBillShipInformation implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private long billShipId;

	private MfCustomers mfCustomers;

	private String attn;

	private String billShipType;

	private String address1;

	private String city;

	private String state;

	private String zip;

	private String customerName;

	private String ordrnum;

	private Set<MfContactInformation> mfContactInformations = new HashSet<MfContactInformation>(
			0);

	public MfBillShipInformation() {
	}

	public MfBillShipInformation(long billShipId) {
		this.billShipId = billShipId;
	}

	public MfBillShipInformation(long billShipId, MfCustomers mfCustomers,
			String attn, String billShipType, String address1, String city,
			String state, String zip, String customerName, String ordrnum,
			Set<MfContactInformation> mfContactInformations) {
		this.billShipId = billShipId;
		this.mfCustomers = mfCustomers;
		this.attn = attn;
		this.billShipType = billShipType;
		this.address1 = address1;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.customerName = customerName;
		this.ordrnum = ordrnum;
		this.mfContactInformations = mfContactInformations;
	}

	@Id
	@Column(name = "BILL_SHIP_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getBillShipId() {
		return this.billShipId;
	}

	public void setBillShipId(long billShipId) {
		this.billShipId = billShipId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER")
	public MfCustomers getMfCustomers() {
		return this.mfCustomers;
	}

	public void setMfCustomers(MfCustomers mfCustomers) {
		this.mfCustomers = mfCustomers;
	}

	@Column(name = "ATTN", length = 14)
	public String getAttn() {
		return this.attn;
	}

	public void setAttn(String attn) {
		this.attn = attn;
	}

	@Column(name = "BILL_SHIP_TYPE", length = 4)
	public String getBillShipType() {
		return this.billShipType;
	}

	public void setBillShipType(String billShipType) {
		this.billShipType = billShipType;
	}

	@Column(name = "ADDRESS1", length = 30)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "CITY", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP", length = 9)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "CUSTOMER_NAME", length = 30)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "ORDRNUM", length = 6)
	public String getOrdrnum() {
		return this.ordrnum;
	}

	public void setOrdrnum(String ordrnum) {
		this.ordrnum = ordrnum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mfBillShipInformation")
	public Set<MfContactInformation> getMfContactInformations() {
		return this.mfContactInformations;
	}

	public void setMfContactInformations(
			Set<MfContactInformation> mfContactInformations) {
		this.mfContactInformations = mfContactInformations;
	}

}
