package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MfContactInformation generated by hbm2java
 */
@Entity
@Table(name = "MF_CONTACT_INFORMATION")
public class MfContactInformation implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private BigDecimal contactId;

	private MfCustomers mfCustomers;

	private MfBillShipInformation mfBillShipInformation;

	private String addrContact;

	private String ordrnum;

	public MfContactInformation() {
	}

	public MfContactInformation(BigDecimal contactId) {
		this.contactId = contactId;
	}

	public MfContactInformation(BigDecimal contactId, MfCustomers mfCustomers,
			MfBillShipInformation mfBillShipInformation, String addrContact,
			String ordrnum) {
		this.contactId = contactId;
		this.mfCustomers = mfCustomers;
		this.mfBillShipInformation = mfBillShipInformation;
		this.addrContact = addrContact;
		this.ordrnum = ordrnum;
	}

	@Id
	@Column(name = "CONTACT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getContactId() {
		return this.contactId;
	}

	public void setContactId(BigDecimal contactId) {
		this.contactId = contactId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER")
	public MfCustomers getMfCustomers() {
		return this.mfCustomers;
	}

	public void setMfCustomers(MfCustomers mfCustomers) {
		this.mfCustomers = mfCustomers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BILL_SHIP_ID")
	public MfBillShipInformation getMfBillShipInformation() {
		return this.mfBillShipInformation;
	}

	public void setMfBillShipInformation(
			MfBillShipInformation mfBillShipInformation) {
		this.mfBillShipInformation = mfBillShipInformation;
	}

	@Column(name = "ADDR_CONTACT", length = 20)
	public String getAddrContact() {
		return this.addrContact;
	}

	public void setAddrContact(String addrContact) {
		this.addrContact = addrContact;
	}

	@Column(name = "ORDRNUM", length = 6)
	public String getOrdrnum() {
		return this.ordrnum;
	}

	public void setOrdrnum(String ordrnum) {
		this.ordrnum = ordrnum;
	}

}
