package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MfCustomers generated by hbm2java
 */
@Entity
@Table(name = "MF_CUSTOMERS")
public class MfCustomers implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private long customer;

	private String custFullname;

	private String custAddr1;

	private String city;

	private String state;

	private String nation;

	private String zip4;

	private String zip5;

	private String addrContact;

	private String phone;

	private Short phoneExt;

	private Integer pid;

	private String instType;

	private Long fax;

	private String flrTerr;

	private String insideTerr;

	private String status;

	private String districtCustNo;

	private String districtPidNo;

	private String institution;

	private Set<MfOrders> mfOrderses = new HashSet<MfOrders>(0);

	private Set<MfProfileInformation> mfProfileInformations = new HashSet<MfProfileInformation>(
			0);

	private Set<MfBillShipInformation> mfBillShipInformations = new HashSet<MfBillShipInformation>(
			0);

	private Set<MfContactInformation> mfContactInformations = new HashSet<MfContactInformation>(
			0);

	public MfCustomers() {
	}

	public MfCustomers(long customer) {
		this.customer = customer;
	}

	public MfCustomers(long customer, String custFullname, String custAddr1,
			String city, String state, String nation, String zip4, String zip5,
			String addrContact, String phone, Short phoneExt, Integer pid,
			String instType, Long fax, String flrTerr, String insideTerr,
			String status, String districtCustNo, String districtPidNo,
			String institution, Set<MfOrders> mfOrderses,
			Set<MfProfileInformation> mfProfileInformations,
			Set<MfBillShipInformation> mfBillShipInformations,
			Set<MfContactInformation> mfContactInformations) {
		this.customer = customer;
		this.custFullname = custFullname;
		this.custAddr1 = custAddr1;
		this.city = city;
		this.state = state;
		this.nation = nation;
		this.zip4 = zip4;
		this.zip5 = zip5;
		this.addrContact = addrContact;
		this.phone = phone;
		this.phoneExt = phoneExt;
		this.pid = pid;
		this.instType = instType;
		this.fax = fax;
		this.flrTerr = flrTerr;
		this.insideTerr = insideTerr;
		this.status = status;
		this.districtCustNo = districtCustNo;
		this.districtPidNo = districtPidNo;
		this.institution = institution;
		this.mfOrderses = mfOrderses;
		this.mfProfileInformations = mfProfileInformations;
		this.mfBillShipInformations = mfBillShipInformations;
		this.mfContactInformations = mfContactInformations;
	}

	@Id
	@Column(name = "CUSTOMER", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCustomer() {
		return this.customer;
	}

	public void setCustomer(long customer) {
		this.customer = customer;
	}

	@Column(name = "CUST_FULLNAME", length = 30)
	public String getCustFullname() {
		return this.custFullname;
	}

	public void setCustFullname(String custFullname) {
		this.custFullname = custFullname;
	}

	@Column(name = "CUST_ADDR1", length = 30)
	public String getCustAddr1() {
		return this.custAddr1;
	}

	public void setCustAddr1(String custAddr1) {
		this.custAddr1 = custAddr1;
	}

	@Column(name = "CITY", length = 26)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "NATION", length = 2)
	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	@Column(name = "ZIP_4", length = 4)
	public String getZip4() {
		return this.zip4;
	}

	public void setZip4(String zip4) {
		this.zip4 = zip4;
	}

	@Column(name = "ZIP_5", length = 5)
	public String getZip5() {
		return this.zip5;
	}

	public void setZip5(String zip5) {
		this.zip5 = zip5;
	}

	@Column(name = "ADDR_CONTACT", length = 20)
	public String getAddrContact() {
		return this.addrContact;
	}

	public void setAddrContact(String addrContact) {
		this.addrContact = addrContact;
	}

	@Column(name = "PHONE", length = 12)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "PHONE_EXT", precision = 4, scale = 0)
	public Short getPhoneExt() {
		return this.phoneExt;
	}

	public void setPhoneExt(Short phoneExt) {
		this.phoneExt = phoneExt;
	}

	@Column(name = "PID", precision = 9, scale = 0)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "INST_TYPE", length = 2)
	public String getInstType() {
		return this.instType;
	}

	public void setInstType(String instType) {
		this.instType = instType;
	}

	@Column(name = "FAX", precision = 11, scale = 0)
	public Long getFax() {
		return this.fax;
	}

	public void setFax(Long fax) {
		this.fax = fax;
	}

	@Column(name = "FLR_TERR", length = 2)
	public String getFlrTerr() {
		return this.flrTerr;
	}

	public void setFlrTerr(String flrTerr) {
		this.flrTerr = flrTerr;
	}

	@Column(name = "INSIDE_TERR", length = 2)
	public String getInsideTerr() {
		return this.insideTerr;
	}

	public void setInsideTerr(String insideTerr) {
		this.insideTerr = insideTerr;
	}

	@Column(name = "STATUS", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "DISTRICT_CUST_NO", length = 8)
	public String getDistrictCustNo() {
		return this.districtCustNo;
	}

	public void setDistrictCustNo(String districtCustNo) {
		this.districtCustNo = districtCustNo;
	}

	@Column(name = "DISTRICT_PID_NO", length = 8)
	public String getDistrictPidNo() {
		return this.districtPidNo;
	}

	public void setDistrictPidNo(String districtPidNo) {
		this.districtPidNo = districtPidNo;
	}

	@Column(name = "INSTITUTION", length = 30)
	public String getInstitution() {
		return this.institution;
	}

	public void setInstitution(String institution) {
		this.institution = institution;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mfCustomers")
	public Set<MfOrders> getMfOrderses() {
		return this.mfOrderses;
	}

	public void setMfOrderses(Set<MfOrders> mfOrderses) {
		this.mfOrderses = mfOrderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mfCustomers")
	public Set<MfProfileInformation> getMfProfileInformations() {
		return this.mfProfileInformations;
	}

	public void setMfProfileInformations(
			Set<MfProfileInformation> mfProfileInformations) {
		this.mfProfileInformations = mfProfileInformations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mfCustomers")
	public Set<MfBillShipInformation> getMfBillShipInformations() {
		return this.mfBillShipInformations;
	}

	public void setMfBillShipInformations(
			Set<MfBillShipInformation> mfBillShipInformations) {
		this.mfBillShipInformations = mfBillShipInformations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mfCustomers")
	public Set<MfContactInformation> getMfContactInformations() {
		return this.mfContactInformations;
	}

	public void setMfContactInformations(
			Set<MfContactInformation> mfContactInformations) {
		this.mfContactInformations = mfContactInformations;
	}

}
