package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MfItems generated by hbm2java
 */
@Entity
@Table(name = "MF_ITEMS")
public class MfItems implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int flrNumber;

	private String title;

	private String author;

	private String isbn;

	private String titleFundDesc;

	private String copyrightYear;

	private Integer sellingPrice;

	private String status;

	private Short bksPerSet;

	private Short kitsPerSet;

	private String readingLevel;

	private String regionalDistrict;

	private String dewey;

	private String nonInventoriedFlag;

	private String nonCatalog;

	private String upc;

	private String itemDescription;

	private String publisher;

	public MfItems() {
	}

	public MfItems(int flrNumber) {
		this.flrNumber = flrNumber;
	}

	public MfItems(int flrNumber, String title, String author, String isbn,
			String titleFundDesc, String copyrightYear, Integer sellingPrice,
			String status, Short bksPerSet, Short kitsPerSet,
			String readingLevel, String regionalDistrict, String dewey,
			String nonInventoriedFlag, String nonCatalog, String upc,
			String itemDescription, String publisher) {
		this.flrNumber = flrNumber;
		this.title = title;
		this.author = author;
		this.isbn = isbn;
		this.titleFundDesc = titleFundDesc;
		this.copyrightYear = copyrightYear;
		this.sellingPrice = sellingPrice;
		this.status = status;
		this.bksPerSet = bksPerSet;
		this.kitsPerSet = kitsPerSet;
		this.readingLevel = readingLevel;
		this.regionalDistrict = regionalDistrict;
		this.dewey = dewey;
		this.nonInventoriedFlag = nonInventoriedFlag;
		this.nonCatalog = nonCatalog;
		this.upc = upc;
		this.itemDescription = itemDescription;
		this.publisher = publisher;
	}

	@Id
	@Column(name = "FLR_NUMBER", unique = true, nullable = false, precision = 7, scale = 0)
	public int getFlrNumber() {
		return this.flrNumber;
	}

	public void setFlrNumber(int flrNumber) {
		this.flrNumber = flrNumber;
	}

	@Column(name = "TITLE", length = 16)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "AUTHOR", length = 40)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "ISBN", length = 16)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "TITLE_FUND_DESC", length = 50)
	public String getTitleFundDesc() {
		return this.titleFundDesc;
	}

	public void setTitleFundDesc(String titleFundDesc) {
		this.titleFundDesc = titleFundDesc;
	}

	@Column(name = "COPYRIGHT_YEAR", length = 4)
	public String getCopyrightYear() {
		return this.copyrightYear;
	}

	public void setCopyrightYear(String copyrightYear) {
		this.copyrightYear = copyrightYear;
	}

	@Column(name = "SELLING_PRICE", precision = 5, scale = 0)
	public Integer getSellingPrice() {
		return this.sellingPrice;
	}

	public void setSellingPrice(Integer sellingPrice) {
		this.sellingPrice = sellingPrice;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "BKS_PER_SET", precision = 3, scale = 0)
	public Short getBksPerSet() {
		return this.bksPerSet;
	}

	public void setBksPerSet(Short bksPerSet) {
		this.bksPerSet = bksPerSet;
	}

	@Column(name = "KITS_PER_SET", precision = 3, scale = 0)
	public Short getKitsPerSet() {
		return this.kitsPerSet;
	}

	public void setKitsPerSet(Short kitsPerSet) {
		this.kitsPerSet = kitsPerSet;
	}

	@Column(name = "READING_LEVEL", length = 30)
	public String getReadingLevel() {
		return this.readingLevel;
	}

	public void setReadingLevel(String readingLevel) {
		this.readingLevel = readingLevel;
	}

	@Column(name = "REGIONAL_DISTRICT", length = 9)
	public String getRegionalDistrict() {
		return this.regionalDistrict;
	}

	public void setRegionalDistrict(String regionalDistrict) {
		this.regionalDistrict = regionalDistrict;
	}

	@Column(name = "DEWEY", length = 1)
	public String getDewey() {
		return this.dewey;
	}

	public void setDewey(String dewey) {
		this.dewey = dewey;
	}

	@Column(name = "NON_INVENTORIED_FLAG", length = 2)
	public String getNonInventoriedFlag() {
		return this.nonInventoriedFlag;
	}

	public void setNonInventoriedFlag(String nonInventoriedFlag) {
		this.nonInventoriedFlag = nonInventoriedFlag;
	}

	@Column(name = "NON_CATALOG", length = 2)
	public String getNonCatalog() {
		return this.nonCatalog;
	}

	public void setNonCatalog(String nonCatalog) {
		this.nonCatalog = nonCatalog;
	}

	@Column(name = "UPC", length = 5)
	public String getUpc() {
		return this.upc;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

	@Column(name = "ITEM_DESCRIPTION", length = 225)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "PUBLISHER", length = 100)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

}
