package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MfOrders generated by hbm2java
 */
@Entity
@Table(name = "MF_ORDERS")
public class MfOrders implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String ordrnum;

	private MfCustomers mfCustomers;

	private Long masterOrderNumber;

	private String country;

	private String custName;

	private String orderStatus;

	private String orderSrcsid;

	private String poNumber;

	private Byte dneAmount;

	private Integer dneQuantity;

	private String taxEmempt;

	private String taxEmemptNum;

	private Set<MfTrackingInformation> mfTrackingInformations = new HashSet<MfTrackingInformation>(
			0);

	public MfOrders() {
	}

	public MfOrders(String ordrnum) {
		this.ordrnum = ordrnum;
	}

	public MfOrders(String ordrnum, MfCustomers mfCustomers,
			Long masterOrderNumber, String country, String custName,
			String orderStatus, String orderSrcsid, String poNumber,
			Byte dneAmount, Integer dneQuantity, String taxEmempt,
			String taxEmemptNum,
			Set<MfTrackingInformation> mfTrackingInformations) {
		this.ordrnum = ordrnum;
		this.mfCustomers = mfCustomers;
		this.masterOrderNumber = masterOrderNumber;
		this.country = country;
		this.custName = custName;
		this.orderStatus = orderStatus;
		this.orderSrcsid = orderSrcsid;
		this.poNumber = poNumber;
		this.dneAmount = dneAmount;
		this.dneQuantity = dneQuantity;
		this.taxEmempt = taxEmempt;
		this.taxEmemptNum = taxEmemptNum;
		this.mfTrackingInformations = mfTrackingInformations;
	}

	@Id
	@Column(name = "ORDRNUM", unique = true, nullable = false, length = 6)
	public String getOrdrnum() {
		return this.ordrnum;
	}

	public void setOrdrnum(String ordrnum) {
		this.ordrnum = ordrnum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTALIAD_ID")
	public MfCustomers getMfCustomers() {
		return this.mfCustomers;
	}

	public void setMfCustomers(MfCustomers mfCustomers) {
		this.mfCustomers = mfCustomers;
	}

	@Column(name = "MASTER_ORDER_NUMBER", precision = 10, scale = 0)
	public Long getMasterOrderNumber() {
		return this.masterOrderNumber;
	}

	public void setMasterOrderNumber(Long masterOrderNumber) {
		this.masterOrderNumber = masterOrderNumber;
	}

	@Column(name = "COUNTRY", length = 30)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "CUST_NAME", length = 30)
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "ORDER_STATUS", length = 1)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "ORDER_SRCSID", length = 1)
	public String getOrderSrcsid() {
		return this.orderSrcsid;
	}

	public void setOrderSrcsid(String orderSrcsid) {
		this.orderSrcsid = orderSrcsid;
	}

	@Column(name = "PO_NUMBER", length = 16)
	public String getPoNumber() {
		return this.poNumber;
	}

	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}

	@Column(name = "DNE_AMOUNT", precision = 2, scale = 0)
	public Byte getDneAmount() {
		return this.dneAmount;
	}

	public void setDneAmount(Byte dneAmount) {
		this.dneAmount = dneAmount;
	}

	@Column(name = "DNE_QUANTITY", precision = 5, scale = 0)
	public Integer getDneQuantity() {
		return this.dneQuantity;
	}

	public void setDneQuantity(Integer dneQuantity) {
		this.dneQuantity = dneQuantity;
	}

	@Column(name = "TAX_EMEMPT", length = 1)
	public String getTaxEmempt() {
		return this.taxEmempt;
	}

	public void setTaxEmempt(String taxEmempt) {
		this.taxEmempt = taxEmempt;
	}

	@Column(name = "TAX_EMEMPT_NUM", length = 20)
	public String getTaxEmemptNum() {
		return this.taxEmemptNum;
	}

	public void setTaxEmemptNum(String taxEmemptNum) {
		this.taxEmemptNum = taxEmemptNum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mfOrders")
	public Set<MfTrackingInformation> getMfTrackingInformations() {
		return this.mfTrackingInformations;
	}

	public void setMfTrackingInformations(
			Set<MfTrackingInformation> mfTrackingInformations) {
		this.mfTrackingInformations = mfTrackingInformations;
	}

}
