package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MfOrdersItems generated by hbm2java
 */
@Entity
@Table(name = "MF_ORDERS_ITEMS")
public class MfOrdersItems implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private MfOrdersItemsId id;

	public MfOrdersItems() {
	}

	public MfOrdersItems(MfOrdersItemsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ordrnum", column = @Column(name = "ORDRNUM", nullable = false, length = 6)),
			@AttributeOverride(name = "flrNumber", column = @Column(name = "FLR_NUMBER", nullable = false, precision = 7, scale = 0)) })
	public MfOrdersItemsId getId() {
		return this.id;
	}

	public void setId(MfOrdersItemsId id) {
		this.id = id;
	}

}
