package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MforderitemsviewId generated by hbm2java
 */
@Embeddable
public class MforderitemsviewId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String ordrnum;

	private String author;

	private Short bksPerSet;

	private String copyrightYear;

	private String dewey;

	private int flrNumber;

	private String isbn;

	private String itemDescription;

	private Short kitsPerSet;

	private String nonCatalog;

	private String nonInventoriedFlag;

	private String publisher;

	private String readingLevel;

	private String regionalDistrict;

	private Integer sellingPrice;

	private String status;

	private String title;

	private String titleFundDesc;

	private String upc;

	public MforderitemsviewId() {
	}

	public MforderitemsviewId(String ordrnum, int flrNumber) {
		this.ordrnum = ordrnum;
		this.flrNumber = flrNumber;
	}

	public MforderitemsviewId(String ordrnum, String author, Short bksPerSet,
			String copyrightYear, String dewey, int flrNumber, String isbn,
			String itemDescription, Short kitsPerSet, String nonCatalog,
			String nonInventoriedFlag, String publisher, String readingLevel,
			String regionalDistrict, Integer sellingPrice, String status,
			String title, String titleFundDesc, String upc) {
		this.ordrnum = ordrnum;
		this.author = author;
		this.bksPerSet = bksPerSet;
		this.copyrightYear = copyrightYear;
		this.dewey = dewey;
		this.flrNumber = flrNumber;
		this.isbn = isbn;
		this.itemDescription = itemDescription;
		this.kitsPerSet = kitsPerSet;
		this.nonCatalog = nonCatalog;
		this.nonInventoriedFlag = nonInventoriedFlag;
		this.publisher = publisher;
		this.readingLevel = readingLevel;
		this.regionalDistrict = regionalDistrict;
		this.sellingPrice = sellingPrice;
		this.status = status;
		this.title = title;
		this.titleFundDesc = titleFundDesc;
		this.upc = upc;
	}

	@Column(name = "ORDRNUM", nullable = false, length = 6)
	public String getOrdrnum() {
		return this.ordrnum;
	}

	public void setOrdrnum(String ordrnum) {
		this.ordrnum = ordrnum;
	}

	@Column(name = "AUTHOR", length = 40)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "BKS_PER_SET", precision = 3, scale = 0)
	public Short getBksPerSet() {
		return this.bksPerSet;
	}

	public void setBksPerSet(Short bksPerSet) {
		this.bksPerSet = bksPerSet;
	}

	@Column(name = "COPYRIGHT_YEAR", length = 4)
	public String getCopyrightYear() {
		return this.copyrightYear;
	}

	public void setCopyrightYear(String copyrightYear) {
		this.copyrightYear = copyrightYear;
	}

	@Column(name = "DEWEY", length = 1)
	public String getDewey() {
		return this.dewey;
	}

	public void setDewey(String dewey) {
		this.dewey = dewey;
	}

	@Column(name = "FLR_NUMBER", nullable = false, precision = 7, scale = 0)
	public int getFlrNumber() {
		return this.flrNumber;
	}

	public void setFlrNumber(int flrNumber) {
		this.flrNumber = flrNumber;
	}

	@Column(name = "ISBN", length = 16)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "ITEM_DESCRIPTION", length = 225)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "KITS_PER_SET", precision = 3, scale = 0)
	public Short getKitsPerSet() {
		return this.kitsPerSet;
	}

	public void setKitsPerSet(Short kitsPerSet) {
		this.kitsPerSet = kitsPerSet;
	}

	@Column(name = "NON_CATALOG", length = 2)
	public String getNonCatalog() {
		return this.nonCatalog;
	}

	public void setNonCatalog(String nonCatalog) {
		this.nonCatalog = nonCatalog;
	}

	@Column(name = "NON_INVENTORIED_FLAG", length = 2)
	public String getNonInventoriedFlag() {
		return this.nonInventoriedFlag;
	}

	public void setNonInventoriedFlag(String nonInventoriedFlag) {
		this.nonInventoriedFlag = nonInventoriedFlag;
	}

	@Column(name = "PUBLISHER", length = 100)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "READING_LEVEL", length = 30)
	public String getReadingLevel() {
		return this.readingLevel;
	}

	public void setReadingLevel(String readingLevel) {
		this.readingLevel = readingLevel;
	}

	@Column(name = "REGIONAL_DISTRICT", length = 9)
	public String getRegionalDistrict() {
		return this.regionalDistrict;
	}

	public void setRegionalDistrict(String regionalDistrict) {
		this.regionalDistrict = regionalDistrict;
	}

	@Column(name = "SELLING_PRICE", precision = 5, scale = 0)
	public Integer getSellingPrice() {
		return this.sellingPrice;
	}

	public void setSellingPrice(Integer sellingPrice) {
		this.sellingPrice = sellingPrice;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "TITLE", length = 16)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "TITLE_FUND_DESC", length = 50)
	public String getTitleFundDesc() {
		return this.titleFundDesc;
	}

	public void setTitleFundDesc(String titleFundDesc) {
		this.titleFundDesc = titleFundDesc;
	}

	@Column(name = "UPC", length = 5)
	public String getUpc() {
		return this.upc;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MforderitemsviewId))
			return false;
		MforderitemsviewId castOther = (MforderitemsviewId) other;

		return ((this.getOrdrnum() == castOther.getOrdrnum()) || (this
				.getOrdrnum() != null && castOther.getOrdrnum() != null && this
				.getOrdrnum().equals(castOther.getOrdrnum())))
				&& ((this.getAuthor() == castOther.getAuthor()) || (this
						.getAuthor() != null && castOther.getAuthor() != null && this
						.getAuthor().equals(castOther.getAuthor())))
				&& ((this.getBksPerSet() == castOther.getBksPerSet()) || (this
						.getBksPerSet() != null
						&& castOther.getBksPerSet() != null && this
						.getBksPerSet().equals(castOther.getBksPerSet())))
				&& ((this.getCopyrightYear() == castOther.getCopyrightYear()) || (this
						.getCopyrightYear() != null
						&& castOther.getCopyrightYear() != null && this
						.getCopyrightYear()
						.equals(castOther.getCopyrightYear())))
				&& ((this.getDewey() == castOther.getDewey()) || (this
						.getDewey() != null && castOther.getDewey() != null && this
						.getDewey().equals(castOther.getDewey())))
				&& (this.getFlrNumber() == castOther.getFlrNumber())
				&& ((this.getIsbn() == castOther.getIsbn()) || (this.getIsbn() != null
						&& castOther.getIsbn() != null && this.getIsbn()
						.equals(castOther.getIsbn())))
				&& ((this.getItemDescription() == castOther
						.getItemDescription()) || (this.getItemDescription() != null
						&& castOther.getItemDescription() != null && this
						.getItemDescription().equals(
								castOther.getItemDescription())))
				&& ((this.getKitsPerSet() == castOther.getKitsPerSet()) || (this
						.getKitsPerSet() != null
						&& castOther.getKitsPerSet() != null && this
						.getKitsPerSet().equals(castOther.getKitsPerSet())))
				&& ((this.getNonCatalog() == castOther.getNonCatalog()) || (this
						.getNonCatalog() != null
						&& castOther.getNonCatalog() != null && this
						.getNonCatalog().equals(castOther.getNonCatalog())))
				&& ((this.getNonInventoriedFlag() == castOther
						.getNonInventoriedFlag()) || (this
						.getNonInventoriedFlag() != null
						&& castOther.getNonInventoriedFlag() != null && this
						.getNonInventoriedFlag().equals(
								castOther.getNonInventoriedFlag())))
				&& ((this.getPublisher() == castOther.getPublisher()) || (this
						.getPublisher() != null
						&& castOther.getPublisher() != null && this
						.getPublisher().equals(castOther.getPublisher())))
				&& ((this.getReadingLevel() == castOther.getReadingLevel()) || (this
						.getReadingLevel() != null
						&& castOther.getReadingLevel() != null && this
						.getReadingLevel().equals(castOther.getReadingLevel())))
				&& ((this.getRegionalDistrict() == castOther
						.getRegionalDistrict()) || (this.getRegionalDistrict() != null
						&& castOther.getRegionalDistrict() != null && this
						.getRegionalDistrict().equals(
								castOther.getRegionalDistrict())))
				&& ((this.getSellingPrice() == castOther.getSellingPrice()) || (this
						.getSellingPrice() != null
						&& castOther.getSellingPrice() != null && this
						.getSellingPrice().equals(castOther.getSellingPrice())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getTitle() == castOther.getTitle()) || (this
						.getTitle() != null && castOther.getTitle() != null && this
						.getTitle().equals(castOther.getTitle())))
				&& ((this.getTitleFundDesc() == castOther.getTitleFundDesc()) || (this
						.getTitleFundDesc() != null
						&& castOther.getTitleFundDesc() != null && this
						.getTitleFundDesc()
						.equals(castOther.getTitleFundDesc())))
				&& ((this.getUpc() == castOther.getUpc()) || (this.getUpc() != null
						&& castOther.getUpc() != null && this.getUpc().equals(
						castOther.getUpc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOrdrnum() == null ? 0 : this.getOrdrnum().hashCode());
		result = 37 * result
				+ (getAuthor() == null ? 0 : this.getAuthor().hashCode());
		result = 37 * result
				+ (getBksPerSet() == null ? 0 : this.getBksPerSet().hashCode());
		result = 37
				* result
				+ (getCopyrightYear() == null ? 0 : this.getCopyrightYear()
						.hashCode());
		result = 37 * result
				+ (getDewey() == null ? 0 : this.getDewey().hashCode());
		result = 37 * result + this.getFlrNumber();
		result = 37 * result
				+ (getIsbn() == null ? 0 : this.getIsbn().hashCode());
		result = 37
				* result
				+ (getItemDescription() == null ? 0 : this.getItemDescription()
						.hashCode());
		result = 37
				* result
				+ (getKitsPerSet() == null ? 0 : this.getKitsPerSet()
						.hashCode());
		result = 37
				* result
				+ (getNonCatalog() == null ? 0 : this.getNonCatalog()
						.hashCode());
		result = 37
				* result
				+ (getNonInventoriedFlag() == null ? 0 : this
						.getNonInventoriedFlag().hashCode());
		result = 37 * result
				+ (getPublisher() == null ? 0 : this.getPublisher().hashCode());
		result = 37
				* result
				+ (getReadingLevel() == null ? 0 : this.getReadingLevel()
						.hashCode());
		result = 37
				* result
				+ (getRegionalDistrict() == null ? 0 : this
						.getRegionalDistrict().hashCode());
		result = 37
				* result
				+ (getSellingPrice() == null ? 0 : this.getSellingPrice()
						.hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result
				+ (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37
				* result
				+ (getTitleFundDesc() == null ? 0 : this.getTitleFundDesc()
						.hashCode());
		result = 37 * result
				+ (getUpc() == null ? 0 : this.getUpc().hashCode());
		return result;
	}

}
