package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MfOrdersItemsId generated by hbm2java
 */
@Embeddable
public class MfOrdersItemsId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String ordrnum;

	private int flrNumber;

	public MfOrdersItemsId() {
	}

	public MfOrdersItemsId(String ordrnum, int flrNumber) {
		this.ordrnum = ordrnum;
		this.flrNumber = flrNumber;
	}

	@Column(name = "ORDRNUM", nullable = false, length = 6)
	public String getOrdrnum() {
		return this.ordrnum;
	}

	public void setOrdrnum(String ordrnum) {
		this.ordrnum = ordrnum;
	}

	@Column(name = "FLR_NUMBER", nullable = false, precision = 7, scale = 0)
	public int getFlrNumber() {
		return this.flrNumber;
	}

	public void setFlrNumber(int flrNumber) {
		this.flrNumber = flrNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MfOrdersItemsId))
			return false;
		MfOrdersItemsId castOther = (MfOrdersItemsId) other;

		return ((this.getOrdrnum() == castOther.getOrdrnum()) || (this
				.getOrdrnum() != null && castOther.getOrdrnum() != null && this
				.getOrdrnum().equals(castOther.getOrdrnum())))
				&& (this.getFlrNumber() == castOther.getFlrNumber());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOrdrnum() == null ? 0 : this.getOrdrnum().hashCode());
		result = 37 * result + this.getFlrNumber();
		return result;
	}

}
