package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mforderitemsview generated by hbm2java
 */
@Entity
@Table(name = "MFORDERITEMSVIEW")
public class Mforderitemsview implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private MforderitemsviewId id;

	public Mforderitemsview() {
	}

	public Mforderitemsview(MforderitemsviewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ordrnum", column = @Column(name = "ORDRNUM", nullable = false, length = 6)),
			@AttributeOverride(name = "author", column = @Column(name = "AUTHOR", length = 40)),
			@AttributeOverride(name = "bksPerSet", column = @Column(name = "BKS_PER_SET", precision = 3, scale = 0)),
			@AttributeOverride(name = "copyrightYear", column = @Column(name = "COPYRIGHT_YEAR", length = 4)),
			@AttributeOverride(name = "dewey", column = @Column(name = "DEWEY", length = 1)),
			@AttributeOverride(name = "flrNumber", column = @Column(name = "FLR_NUMBER", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "isbn", column = @Column(name = "ISBN", length = 16)),
			@AttributeOverride(name = "itemDescription", column = @Column(name = "ITEM_DESCRIPTION", length = 225)),
			@AttributeOverride(name = "kitsPerSet", column = @Column(name = "KITS_PER_SET", precision = 3, scale = 0)),
			@AttributeOverride(name = "nonCatalog", column = @Column(name = "NON_CATALOG", length = 2)),
			@AttributeOverride(name = "nonInventoriedFlag", column = @Column(name = "NON_INVENTORIED_FLAG", length = 2)),
			@AttributeOverride(name = "publisher", column = @Column(name = "PUBLISHER", length = 100)),
			@AttributeOverride(name = "readingLevel", column = @Column(name = "READING_LEVEL", length = 30)),
			@AttributeOverride(name = "regionalDistrict", column = @Column(name = "REGIONAL_DISTRICT", length = 9)),
			@AttributeOverride(name = "sellingPrice", column = @Column(name = "SELLING_PRICE", precision = 5, scale = 0)),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", length = 1)),
			@AttributeOverride(name = "title", column = @Column(name = "TITLE", length = 16)),
			@AttributeOverride(name = "titleFundDesc", column = @Column(name = "TITLE_FUND_DESC", length = 50)),
			@AttributeOverride(name = "upc", column = @Column(name = "UPC", length = 5)) })
	public MforderitemsviewId getId() {
		return this.id;
	}

	public void setId(MforderitemsviewId id) {
		this.id = id;
	}

}
