package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MfProfileInformation generated by hbm2java
 */
@Entity
@Table(name = "MF_PROFILE_INFORMATION")
public class MfProfileInformation implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private BigDecimal profileId;

	private MfCustomers mfCustomers;

	public MfProfileInformation() {
	}

	public MfProfileInformation(BigDecimal profileId) {
		this.profileId = profileId;
	}

	public MfProfileInformation(BigDecimal profileId, MfCustomers mfCustomers) {
		this.profileId = profileId;
		this.mfCustomers = mfCustomers;
	}

	@Id
	@Column(name = "PROFILE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProfileId() {
		return this.profileId;
	}

	public void setProfileId(BigDecimal profileId) {
		this.profileId = profileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER")
	public MfCustomers getMfCustomers() {
		return this.mfCustomers;
	}

	public void setMfCustomers(MfCustomers mfCustomers) {
		this.mfCustomers = mfCustomers;
	}

}
