package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MfTrackingInformation generated by hbm2java
 */
@Entity
@Table(name = "MF_TRACKING_INFORMATION")
public class MfTrackingInformation implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private BigDecimal trackingId;

	private MfOrders mfOrders;

	private String shipmentStatus;

	public MfTrackingInformation() {
	}

	public MfTrackingInformation(BigDecimal trackingId) {
		this.trackingId = trackingId;
	}

	public MfTrackingInformation(BigDecimal trackingId, MfOrders mfOrders,
			String shipmentStatus) {
		this.trackingId = trackingId;
		this.mfOrders = mfOrders;
		this.shipmentStatus = shipmentStatus;
	}

	@Id
	@Column(name = "TRACKING_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTrackingId() {
		return this.trackingId;
	}

	public void setTrackingId(BigDecimal trackingId) {
		this.trackingId = trackingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDRNUM")
	public MfOrders getMfOrders() {
		return this.mfOrders;
	}

	public void setMfOrders(MfOrders mfOrders) {
		this.mfOrders = mfOrders;
	}

	@Column(name = "SHIPMENT_STATUS", length = 10)
	public String getShipmentStatus() {
		return this.shipmentStatus;
	}

	public void setShipmentStatus(String shipmentStatus) {
		this.shipmentStatus = shipmentStatus;
	}

}
