package com.follett.coms.service.models;

// Generated 5 Oct, 2015 11:48:28 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Orderitemsview generated by hbm2java
 */
/**
 * @author amahajan
 *
 */
@Entity
@Table(name = "ORDERITEMSVIEW")
@NamedQuery(name = "fetch", query = "FROM Orderitemsview o WHERE o.id.orderNumber =1000 AND o.id.orderSuffix ='a'")
public class Orderitemsview implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private OrderitemsviewId id;

	private String bookNumber;

	private String author;

	private String bookNotes;

	private String bookType;

	private Short copyrightYear;

	private String edition;

	private String fesBookNumber;

	// this field is mapped with isbn10 and 13 is still remaining.
	private String isbn;

	private String itemDescription;

	private String productCategory;

	private String publisher;

	private String publisherCode;

	private String publisherItemNum;

	private Short readingLevel;

	private String subject;

	private String title;

	private String titleInformation;

	private String upcCode;

	private String vendorNumber;

	private String vendorProductNumber;

	private String warehouseCode;

	private String waveAccRedIntLvl;

	private As400Orders as400Orders;

	/**
	 * @return the as400Orders
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ORDER_NUMBER", referencedColumnName = "ORDER_NUMBER", updatable = false, insertable = false),
			@JoinColumn(name = "ORDER_SUFFIX", referencedColumnName = "ORDER_SUFFIX", updatable = false, insertable = false) })
	public As400Orders getAs400Orders() {
		return as400Orders;
	}

	/**
	 * @param as400Orders
	 *            the as400Orders to set
	 */
	public void setAs400Orders(As400Orders as400Orders) {
		this.as400Orders = as400Orders;
	}

	@Column(name = "AUTHOR", length = 50)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "BOOK_NOTES", length = 60)
	public String getBookNotes() {
		return this.bookNotes;
	}

	public void setBookNotes(String bookNotes) {
		this.bookNotes = bookNotes;
	}

	@Column(name = "BOOK_TYPE", length = 30)
	public String getBookType() {
		return this.bookType;
	}

	public void setBookType(String bookType) {
		this.bookType = bookType;
	}

	@Column(name = "COPYRIGHT_YEAR", precision = 4, scale = 0)
	public Short getCopyrightYear() {
		return this.copyrightYear;
	}

	public void setCopyrightYear(Short copyrightYear) {
		this.copyrightYear = copyrightYear;
	}

	@Column(name = "EDITION", length = 20)
	public String getEdition() {
		return this.edition;
	}

	public void setEdition(String edition) {
		this.edition = edition;
	}

	@Column(name = "FES_BOOK_NUMBER", length = 7)
	public String getFesBookNumber() {
		return this.fesBookNumber;
	}

	public void setFesBookNumber(String fesBookNumber) {
		this.fesBookNumber = fesBookNumber;
	}

	@Column(name = "ISBN10", length = 13)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "ITEM_DESCRIPTION", length = 225)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "PRODUCT_CATEGORY", length = 20)
	public String getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(String productCategory) {
		this.productCategory = productCategory;
	}

	@Column(name = "PUBLISHER", length = 100)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "PUBLISHER_CODE", length = 4)
	public String getPublisherCode() {
		return this.publisherCode;
	}

	public void setPublisherCode(String publisherCode) {
		this.publisherCode = publisherCode;
	}

	@Column(name = "PUBLISHER_ITEM_NUM", length = 7)
	public String getPublisherItemNum() {
		return this.publisherItemNum;
	}

	public void setPublisherItemNum(String publisherItemNum) {
		this.publisherItemNum = publisherItemNum;
	}

	@Column(name = "READING_LEVEL", precision = 4, scale = 0)
	public Short getReadingLevel() {
		return this.readingLevel;
	}

	public void setReadingLevel(Short readingLevel) {
		this.readingLevel = readingLevel;
	}

	@Column(name = "SUBJECT", length = 4)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "TITLE", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "TITLE_INFORMATION", length = 100)
	public String getTitleInformation() {
		return this.titleInformation;
	}

	public void setTitleInformation(String titleInformation) {
		this.titleInformation = titleInformation;
	}

	@Column(name = "UPC_CODE", length = 11)
	public String getUpcCode() {
		return this.upcCode;
	}

	public void setUpcCode(String upcCode) {
		this.upcCode = upcCode;
	}

	@Column(name = "VENDOR_NUMBER", length = 4)
	public String getVendorNumber() {
		return this.vendorNumber;
	}

	public void setVendorNumber(String vendorNumber) {
		this.vendorNumber = vendorNumber;
	}

	@Column(name = "VENDOR_PRODUCT_NUMBER", length = 10)
	public String getVendorProductNumber() {
		return this.vendorProductNumber;
	}

	public void setVendorProductNumber(String vendorProductNumber) {
		this.vendorProductNumber = vendorProductNumber;
	}

	@Column(name = "WAREHOUSE_CODE", length = 10)
	public String getWarehouseCode() {
		return this.warehouseCode;
	}

	public void setWarehouseCode(String warehouseCode) {
		this.warehouseCode = warehouseCode;
	}

	/**
	 * @return the id
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "orderNumber", column = @Column(name = "ORDER_NUMBER", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "orderSuffix", column = @Column(name = "ORDER_SUFFIX", nullable = false, length = 2)), })
	public OrderitemsviewId getId() {
		return id;
	}

	/**
	 * @return the waveAccRedIntLvl
	 */
	@Column(name = "WAVE_ACC_RED_INT_LVL", length = 2)
	public String getWaveAccRedIntLvl() {
		return waveAccRedIntLvl;
	}

	/**
	 * @param waveAccRedIntLvl
	 *            the waveAccRedIntLvl to set
	 */
	public void setWaveAccRedIntLvl(String waveAccRedIntLvl) {
		this.waveAccRedIntLvl = waveAccRedIntLvl;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(OrderitemsviewId id) {
		this.id = id;
	}

	@Column(name = "BOOK_NUMBER", nullable = false, length = 7)
	public String getBookNumber() {
		return this.bookNumber;
	}

	public void setBookNumber(String bookNumber) {
		this.bookNumber = bookNumber;
	}
}
